// Deterministic mock data for Carreira module — all screens
// Matches the prototype values in 05-carreira-redesign.html

export const MOCK_PROFILE = {
  id: 'mock-profile-1',
  user_id: 'mock-user',
  current_title: 'Desenvolvedor Senior',
  current_company: 'TechCorp Brasil',
  field: 'technology' as const,
  level: 'senior' as const,
  gross_salary: 12500,
  start_date: '2024-03-01',
  sync_salary_to_finance: true,
  created_at: '2024-03-01T00:00:00Z',
  updated_at: '2024-03-01T00:00:00Z',
}

export const MOCK_SKILLS = [
  { id: 'sk-1', user_id: 'mock-user', name: 'React', category: 'hard_skill' as const, proficiency_level: 5, notes: '5 anos de experiência', linked_track_ids: [], created_at: '2021-01-01' },
  { id: 'sk-2', user_id: 'mock-user', name: 'TypeScript', category: 'hard_skill' as const, proficiency_level: 4, notes: '4 anos', linked_track_ids: [], created_at: '2022-01-01' },
  { id: 'sk-3', user_id: 'mock-user', name: 'Node.js', category: 'hard_skill' as const, proficiency_level: 4, notes: '3 anos', linked_track_ids: [], created_at: '2023-01-01' },
  { id: 'sk-4', user_id: 'mock-user', name: 'Docker', category: 'hard_skill' as const, proficiency_level: 3, notes: '2 anos', linked_track_ids: [], created_at: '2024-01-01' },
  { id: 'sk-5', user_id: 'mock-user', name: 'Python', category: 'hard_skill' as const, proficiency_level: 3, notes: '2 anos', linked_track_ids: [], created_at: '2024-01-01' },
  { id: 'sk-6', user_id: 'mock-user', name: 'PostgreSQL', category: 'hard_skill' as const, proficiency_level: 4, notes: '3 anos', linked_track_ids: [], created_at: '2023-01-01' },
  { id: 'sk-7', user_id: 'mock-user', name: 'Next.js', category: 'hard_skill' as const, proficiency_level: 4, notes: '2 anos', linked_track_ids: [], created_at: '2024-01-01' },
  { id: 'sk-8', user_id: 'mock-user', name: 'GraphQL', category: 'hard_skill' as const, proficiency_level: 3, notes: '1 ano', linked_track_ids: [], created_at: '2025-01-01' },
  { id: 'sk-9', user_id: 'mock-user', name: 'Terraform', category: 'hard_skill' as const, proficiency_level: 2, notes: '1 ano', linked_track_ids: [], created_at: '2025-01-01' },
  { id: 'sk-10', user_id: 'mock-user', name: 'Redis', category: 'hard_skill' as const, proficiency_level: 3, notes: '2 anos', linked_track_ids: [], created_at: '2024-01-01' },
  { id: 'sk-11', user_id: 'mock-user', name: 'Liderança', category: 'soft_skill' as const, proficiency_level: 3, notes: '2 anos liderando squad', linked_track_ids: [], created_at: '2024-01-01' },
  { id: 'sk-12', user_id: 'mock-user', name: 'Comunicação', category: 'soft_skill' as const, proficiency_level: 4, notes: 'Apresentações técnicas', linked_track_ids: [], created_at: '2022-01-01' },
  { id: 'sk-13', user_id: 'mock-user', name: 'Negociação', category: 'soft_skill' as const, proficiency_level: 3, notes: null, linked_track_ids: [], created_at: '2023-01-01' },
  { id: 'sk-14', user_id: 'mock-user', name: 'Mentoria', category: 'soft_skill' as const, proficiency_level: 3, notes: 'Mentoria de 2 juniors', linked_track_ids: [], created_at: '2025-01-01' },
  { id: 'sk-15', user_id: 'mock-user', name: 'Inglês', category: 'language' as const, proficiency_level: 4, notes: 'C1 — fluente', linked_track_ids: [], created_at: '2020-01-01' },
  { id: 'sk-16', user_id: 'mock-user', name: 'Espanhol', category: 'language' as const, proficiency_level: 2, notes: 'A2 — básico', linked_track_ids: [], created_at: '2025-01-01' },
  { id: 'sk-17', user_id: 'mock-user', name: 'AWS Solutions Architect', category: 'certification' as const, proficiency_level: 5, notes: 'Certificado jan 2025', linked_track_ids: [], created_at: '2025-01-01' },
  { id: 'sk-18', user_id: 'mock-user', name: 'Scrum Master', category: 'certification' as const, proficiency_level: 4, notes: 'PSM I', linked_track_ids: [], created_at: '2023-06-01' },
]

export const MOCK_ROADMAPS = [
  {
    id: 'rm-1',
    user_id: 'mock-user',
    name: 'Tech Lead em 2 anos',
    status: 'active' as const,
    progress: 67,
    current_title: 'Senior',
    target_title: 'Tech Lead',
    target_salary: 18000,
    target_date: '2027-12-01',
    linked_objective_id: null,
    created_at: '2024-01-01',
    steps: [
      { id: 'st-1', title: 'Certificação AWS', status: 'completed' as const, target_date: '2025-01-15', description: 'Obter AWS Solutions Architect Associate', sort_order: 0 },
      { id: 'st-2', title: 'Liderar squad', status: 'completed' as const, target_date: '2025-06-01', description: 'Assumir liderança técnica de um squad de 4 devs', sort_order: 1 },
      { id: 'st-3', title: 'Mentoria 2 juniors', status: 'completed' as const, target_date: '2025-09-01', description: 'Mentorar pelo menos 2 desenvolvedores junior', sort_order: 2 },
      { id: 'st-4', title: 'Arquitetura de sistema', status: 'in_progress' as const, target_date: '2026-03-01', description: 'Projetar e documentar a arquitetura de pelo menos 2 sistemas end-to-end, com decisões de trade-off documentadas.', sort_order: 3 },
      { id: 'st-5', title: 'Gestão de projeto', status: 'pending' as const, target_date: '2026-08-01', description: 'Gerir um projeto do início ao fim com cronograma e stakeholders', sort_order: 4 },
      { id: 'st-6', title: 'Promoção Tech Lead', status: 'pending' as const, target_date: '2027-12-01', description: 'Ser promovido oficialmente a Tech Lead', sort_order: 5 },
    ],
  },
  {
    id: 'rm-2',
    user_id: 'mock-user',
    name: 'Transição para Senior',
    status: 'completed' as const,
    progress: 100,
    current_title: 'Pleno',
    target_title: 'Senior',
    target_salary: 12500,
    target_date: '2024-03-01',
    linked_objective_id: null,
    created_at: '2022-06-01',
    steps: [
      { id: 'st-7', title: 'Dominar React', status: 'completed' as const, target_date: '2022-12-01', description: null, sort_order: 0 },
      { id: 'st-8', title: 'Projeto solo', status: 'completed' as const, target_date: '2023-06-01', description: null, sort_order: 1 },
      { id: 'st-9', title: 'Code review', status: 'completed' as const, target_date: '2023-12-01', description: null, sort_order: 2 },
      { id: 'st-10', title: 'Promoção Senior', status: 'completed' as const, target_date: '2024-03-01', description: null, sort_order: 3 },
    ],
  },
  {
    id: 'rm-3',
    user_id: 'mock-user',
    name: 'MBA em Gestão',
    status: 'paused' as const,
    progress: 25,
    current_title: 'Senior',
    target_title: 'Engineering Manager',
    target_salary: null,
    target_date: null,
    linked_objective_id: null,
    created_at: '2025-01-01',
    steps: [
      { id: 'st-11', title: 'Pesquisar programas', status: 'completed' as const, target_date: null, description: null, sort_order: 0 },
      { id: 'st-12', title: 'Aplicar para MBA', status: 'pending' as const, target_date: null, description: null, sort_order: 1 },
      { id: 'st-13', title: 'Cursar MBA', status: 'pending' as const, target_date: null, description: null, sort_order: 2 },
      { id: 'st-14', title: 'Transição de carreira', status: 'pending' as const, target_date: null, description: null, sort_order: 3 },
    ],
  },
]

export const MOCK_HISTORY = [
  {
    id: 'h-1',
    user_id: 'mock-user',
    title: 'Promoção a Senior',
    company: 'TechCorp Brasil',
    field: 'technology',
    level: 'senior',
    salary: 12500,
    start_date: '2024-03-01',
    end_date: null,
    change_type: 'promotion' as const,
    notes: 'Promoção após liderar projeto de migração de microservices',
  },
  {
    id: 'h-2',
    user_id: 'mock-user',
    title: 'Engenheiro de Software Pleno',
    company: 'TechCorp Brasil',
    field: 'technology',
    level: 'mid',
    salary: 9200,
    start_date: '2022-01-10',
    end_date: '2024-03-01',
    change_type: 'company_change' as const,
    notes: 'Mudança de empresa com aumento salarial significativo',
  },
  {
    id: 'h-3',
    user_id: 'mock-user',
    title: 'Ajuste salarial',
    company: 'Startup Flow',
    field: 'technology',
    level: 'mid',
    salary: 7500,
    start_date: '2021-01-01',
    end_date: '2021-12-31',
    change_type: 'salary_change' as const,
    notes: 'Reajuste anual acima da inflação',
  },
  {
    id: 'h-4',
    user_id: 'mock-user',
    title: 'Promoção a Pleno',
    company: 'Startup Flow',
    field: 'technology',
    level: 'mid',
    salary: 6500,
    start_date: '2020-08-01',
    end_date: '2020-12-31',
    change_type: 'promotion' as const,
    notes: 'Promovido após entregar feature de pagamentos sozinho',
  },
  {
    id: 'h-5',
    user_id: 'mock-user',
    title: 'Mudança de área',
    company: 'Startup Flow',
    field: 'technology',
    level: 'junior',
    salary: 5100,
    start_date: '2020-01-01',
    end_date: '2020-07-31',
    change_type: 'lateral' as const,
    notes: 'Transição de Frontend para Fullstack',
  },
  {
    id: 'h-6',
    user_id: 'mock-user',
    title: 'Primeiro emprego',
    company: 'Startup Flow',
    field: 'technology',
    level: 'junior',
    salary: 5100,
    start_date: '2019-03-01',
    end_date: '2019-12-31',
    change_type: 'initial' as const,
    notes: 'Primeiro emprego como desenvolvedor junior',
  },
]

// XP data matching prototype (Level 12, 14 dias, 1250/2000)
export const MOCK_XP = {
  level: 12,
  levelTitle: 'Arquiteto Digital',
  streak: 14,
  currentXp: 1250,
  nextLevelXp: 2000,
  totalXpEarned: 12500,
}

// Category colors for skills
export const SKILL_CATEGORY_COLORS: Record<string, string> = {
  hard_skill: '#3b82f6',
  soft_skill: '#10b981',
  language: '#f59e0b',
  certification: '#a855f7',
}

// Years of experience per skill (for table display)
export const SKILL_YEARS: Record<string, string> = {
  'sk-1': '5 anos',
  'sk-2': '4 anos',
  'sk-3': '3 anos',
  'sk-4': '2 anos',
  'sk-5': '2 anos',
  'sk-6': '3 anos',
  'sk-7': '2 anos',
  'sk-8': '1 ano',
  'sk-9': '1 ano',
  'sk-10': '2 anos',
  'sk-11': '2 anos',
  'sk-12': '4 anos',
  'sk-13': '2 anos',
  'sk-14': '1 ano',
  'sk-15': '6 anos',
  'sk-16': '1 ano',
  'sk-17': 'jan 2025',
  'sk-18': 'jun 2023',
}
